# Site settings
title: Ian Livingstone
email: ianrlivingstone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  hello -- thigns go here
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ianlivingstone.ca" # the base hostname & protocol for your site
twitter_username: ianlivingstone
github_username:  ianlivingstone
linkedin_username: irlivingstone

# Build settings
markdown: kramdown
exclude: ["_bin"]
