# Site settings
title: Ian Livingstone
email: ianrlivingstone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Ian Livingstone\'s personal blog on building products from the ground up and scaling companies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ianlivingstone.ca" # the base hostname & protocol for your site
twitter_username: ianlivingstone
github_username:  ianlivingstone
linkedin_username: irlivingstone
google_plus: ianlivingstoner

# Pagination settings
paginate: 5

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
relative_permalinks: true
exclude: ["_bin"]
gems:
    - jekyll-sitemap
