#!/usr/bin/env bash
set -e -o pipefail # make this a safe environment :)

pushd `dirname $0` > /dev/null
    SCRIPTPATH=`pwd`
    pushd "$SCRIPTPATH/.." > /dev/null
        ROOTPATH=`pwd`
    popd > /dev/null
popd > /dev/null

extra_args=()
if [[ ! -z "$DEBUG" ]]
then
    echo "Docker will run in DEBUG mode"
    extra_args+=(
        "--env='NOISY_INSTALL=true'"
    )
fi

function run {
    mode=$1

    cmd="sudo -u jekyll JEKYLL_ENV=$mode /usr/local/bin/jekyll serve \
        --config _config.yml,_config_dev.yml"

    case $mode in
        "development")
            echo "Serving in development mode"
            cmd="$cmd --watch --drafts --trace "
            ;;
        "production")
            echo "Serving in production mode"
            ;;
        *)
            echo "A mode must be provided to the run function"
            exit 1
            ;;
    esac

    cmdtoeval="docker run \
            --rm --volume=$ROOTPATH:/srv/jekyll \
            -p 4000:4000 \
            -it jekyll/pages:latest \
            $cmd"

    echo "cmd: $cmdtoeval"
    eval "$cmdtoeval"
}

case $1 in
    "dev")
        run "development"
        ;;
    "prod")
        run "production"
        ;;
    "help")
        echo "Use the following commands to view the blog (docker required)"
        echo -e "\tblog dev\tto run the blog in development mode (auto rebuild and drafts)"
        echo -e "\tblog prod\tto run the blog in production mode (no drafts)"
        ;;
    *)
        echo "unknown command try 'blog help'"
    ;;
esac
