#!/usr/bin/env bash
set -e -o pipefail # make this a safe environment :)

pushd `dirname $0` > /dev/null
    SCRIPTPATH=`pwd`
    pushd "$SCRIPTPATH/.." > /dev/null
        ROOTPATH=`pwd`
    popd > /dev/null
popd > /dev/null

extra_args=()
if [[ ! -z "$DEBUG" ]]
then
    echo "Docker will run in DEBUG mode"
    extra_args+=(
        "--env='NOISY_INSTALL=true'"
    )
fi

function run {
    mode=$1
    cmd="sudo -u jekyll /usr/local/bin/jekyll serve"
    case $mode in
        "dev")
            echo "Serving in development mode"
            extra_args+=(
                "--env='JEKYLL_ENV=development'"
            )
            cmd="$cmd --watch --drafts --trace"
            ;;
        "prod")
            echo "Serving in production mode"
            ;;
        *)
            echo "A mode must be provided to the run function"
            exit 1
            ;;
    esac

    eval "docker run --rm --volume=$ROOTPATH:/srv/jekyll \
            -p 4000:4000 \
            ${extra_args[*]} \
            -it jekyll/pages:latest \
            $cmd"
}

case $1 in
    "dev")
        run "dev"
        ;;
    "prod")
        run "prod"
        ;;
    "help")
        echo "Use the following commands to view the blog (docker required)"
        echo -e "\tblog dev\tto run the blog in development mode (auto rebuild and drafts)"
        echo -e "\tblog prod\tto run the blog in production mode (no drafts)"
        ;;
    *)
        echo "unknown command try 'blog help'"
    ;;
esac
